// Generated by CoffeeScript 1.7.1
(function() {
  var Constants, Core;

  Constants = (function() {
    function Constants() {}

    Constants.SELECTOR_TILE = ".tile-content";

    Constants.SELECTOR_NAV = ".navitem nav";

    return Constants;

  })();

  Core = (function() {
    var debug;

    function Core() {}

    Core.prototype.bgSrc = "/" + ($(window).width()) + "/" + ($(window).height() - 90) + "/";

    debug = function(msg) {
      return console.log("Core: " + msg);
    };

    Core.prototype.construct = function() {};

    Core.prototype.handleHash = function() {
      var i, _i, _results;
      if (window.location.hash !== "") {
        debug("Hash detected");
        _results = [];
        for (i = _i = 0; _i <= 7; i = ++_i) {
          debug(i);
          if ("#" + tileResolver[i][1] === window.location.hash) {
            tileOnClickHandler(i + 1)();
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };

    Core.prototype.injectBackground = function() {
      debug(this.bgSrc);
      return $("<img>", {
        src: this.bgSrc + "bg"
      }).appendTo($("#bg")).load(function() {
        return $(this).fadeIn(300);
      });
    };

    Core.prototype.injectTileBackgrounds = function() {
      var i, _i, _results;
      _results = [];
      for (i = _i = 12; _i >= 0; i = --_i) {
        $("#" + i).css({
          "background-image": "url(" + (this.bgSrc + i) + ")"
        });
        _results.push($("#" + i).click(tileOnClickHandler(i)));
      }
      return _results;
    };

    Core.prototype.loadEffects = function() {
      var stl;
      stl = $(Constants.SELECTOR_TILE);
      return stl.each(function(index, obj) {
        obj = $(obj);
        return obj.hover(function() {
          obj.children("a").children(".hoveroverlay").animate({
            opacity: "0.7"
          }, 100);
          return $(stl.not(".hoveroverlay")[index - 1]).children(".hoveroverlay").animate({
            opacity: "0"
          }, 100);
        }, function() {
          obj.children("a").children(".hoveroverlay").animate({
            opacity: "0"
          }, 100);
          return $(stl[index - 1]).children("a").children(".hoveroverlay").animate({
            opacity: "0"
          }, 100);
        });
      });
    };

    return Core;

  })();

  $(function() {
    var c;
    c = new Core;
    c.handleHash();
    c.injectBackground();
    c.injectTileBackgrounds();
    return c.loadEffects();
  });

}).call(this);
