// Generated by CoffeeScript 1.7.1
var Presse,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Presse = (function(_super) {
  __extends(Presse, _super);

  Presse.ready = false;

  Presse.wall = null;

  function Presse() {
    Presse.__super__.constructor.call(this);
  }

  Presse.prototype.onGenerateMarkup = function() {};

  Presse.prototype.onLoad = function() {
    return $.getScript("code/sly.min.js", function() {
      var sly;
      sly = new Sly(".presse-frame", {
        horizontal: 1,
        itemNav: 'basic',
        activateOn: 'click',
        mouseDragging: 1,
        touchDragging: 1,
        releaseSwing: 1,
        smart: 1,
        dynamicHandle: 1,
        speed: 300,
        easing: 'swing',
        scrollBy: 1
      }).init();
      return $(".presse-frame").css({
        top: $(window).height() / 2 - $(".presse-frame").height() / 2
      });
    });
  };

  Presse.prototype.dependencyHook = function() {
    return ["code/sly.min.js"];
  };

  Presse.prototype.onScrollFinished = function() {};

  Presse.prototype.onUnloadChild = function() {};

  return Presse;

})(ChildPage);

window.core.insertChildPage(new Presse());
