// Generated by CoffeeScript 1.7.1
var Presse,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Presse = (function(_super) {
  __extends(Presse, _super);

  Presse.ready = false;

  Presse.wall = null;

  function Presse() {
    Presse.__super__.constructor.call(this);
  }

  Presse.prototype.onGenerateMarkup = function() {};

  Presse.prototype.onLoad = function() {
    return $.getScript("code/freewall.js", function(data, textStatus, jqxhr) {
      var wall;
      this.ready = true;
      wall = new freewall(".presseart");
      wall.reset({
        selector: '.brick',
        cellW: function(container) {
          return 450;
        },
        cellH: function(container) {
          var cellHeight;
          cellHeight = container / 3;
          return cellHeight - 20;
        },
        fixSize: true,
        gutterY: 20,
        gutterX: 20,
        animate: false,
        onResize: function() {
          return wall.fitWidth();
        }
      });
      return wall.fitWidth();
    });
  };

  Presse.prototype.onScrollFinished = function() {};

  Presse.prototype.onUnloadChild = function() {};

  return Presse;

})(ChildPage);

window.core.insertChildPage(new Presse());
