// Generated by CoffeeScript 1.11.1
var Shop,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Shop = (function(superClass) {
  extend(Shop, superClass);

  function Shop() {
    Shop.__super__.constructor.call(this);
    window.core.requestFunction("ContentViewer.requestInstance", (function(_this) {
      return function(cView) {
        return _this.contentViewer = cView();
      };
    })(this));
    this.mode = "";
  }

  Shop.prototype.onLoad = function() {
    window.core.setMetaDesc("Chorknaben CD 'Cantate Domino', DVD 'Hinter den Stimmen' kaufen", "Shop");
    return $(".button").click(function() {
      this.contentViewer.close();
      return this.contentViewer.reset();
    });
  };

  Shop.prototype.onUnloadChild = function() {
    return window.core.revMetaDesc();
  };

  Shop.prototype.notifyHashChange = function(newHash) {
    var bothtiles, btnMehrInfo;
    if (newHash === "/cd" || newHash === "/dvd") {
      this.contentViewer.reset();
      btnMehrInfo = $("." + newHash.substring(1));
      this.mode = newHash;
      bothtiles = $(".tile-shop");
      this.contentViewer.open({
        left: function() {
          return $(bothtiles[0]).offset().left;
        },
        top: function() {
          return $(bothtiles[0]).offset().top;
        },
        height: function() {
          return $(bothtiles[1]).height();
        },
        width: function() {
          return 1010;
        },
        title: "Unsere " + this.mode.substring(1).toUpperCase(),
        caption: "Mehr Informationen",
        revertHash: "#!/shop",
        content: (function() {
          if (newHash === "/cd") {
            return $("#contentviewwrapper #cd").html();
          } else if (newHash === "/dvd") {
            return $("#contentviewwrapper #dvd").html();
          }
        })(),
        animate: true,
        startingPos: {
          left: btnMehrInfo.offset().left,
          top: btnMehrInfo.offset().top,
          height: btnMehrInfo.height(),
          width: btnMehrInfo.width()
        }
      });
    }
    return $("a.wrapping").click((function(_this) {
      return function(e) {
        e.preventDefault();
        e.stopPropagation();
        _this.contentViewer.close();
        return location.href = "#!/musik";
      };
    })(this));
  };

  return Shop;

})(ChildPage);

window.core.insertChildPage(new Shop());
