// Generated by CoffeeScript 1.7.1
var Shop,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Shop = (function(_super) {
  __extends(Shop, _super);

  function Shop() {
    Shop.__super__.constructor.call(this);
  }

  return Shop;

})(ChildPage);

window.core.insertChildPage(new Shop());
