// Generated by CoffeeScript 1.7.1
var Stiftung,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Stiftung = (function(_super) {
  __extends(Stiftung, _super);

  function Stiftung() {
    Stiftung.__super__.constructor.call(this);
  }

  Stiftung.prototype.onLoad = function() {};

  Stiftung.prototype.onUnloadChild = function() {};

  Stiftung.prototype.notifyHashChange = function(newHash) {
    if (newHash === "/" || newHash === "") {
      $(".stiftung-main-area").eq(1).addClass("nodisplay");
      $(".stiftung-main-area").eq(0).removeClass("nodisplay");
    }
    if (newHash === "/forderverein") {
      $(".stiftung-main-area").eq(0).addClass("nodisplay");
      return $(".stiftung-main-area").eq(1).removeClass("nodisplay");
    }
  };

  return Stiftung;

})(ChildPage);

window.core.insertChildPage(new Stiftung());
