// Generated by CoffeeScript 1.7.1
var UberunsReise,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

UberunsReise = (function(_super) {
  __extends(UberunsReise, _super);

  function UberunsReise() {
    this.reisehack = __bind(this.reisehack, this);
    this.core = window.core;
  }

  UberunsReise.prototype.onLoad = function() {};

  UberunsReise.prototype.onDOMVisible = function() {
    this.reisehack();
    return $(window).on("resize", this.reisehack);
  };

  UberunsReise.prototype.onUnloadChild = function() {
    return $(window).off("resize", this.reisehack);
  };

  UberunsReise.prototype.notifyHashChange = function(newHash) {
    console.log("getting hash: " + newHash);
    return this.core.requestFunction("Tile.load", function(load) {
      newHash = newHash.substr(1, newHash.length);
      this.core.registerTaker("dontHandle", true);
      load("Über uns", "uberuns-" + newHash, "uberuns", "uberuns/" + newHash, true);
      return this.core.requestTaker("dontHandle");
    }, $.noop);
  };

  UberunsReise.prototype.reisehack = function() {
    var wReiseTile;
    wReiseTile = $(".reise-tile").eq(0).height();
    return $("#reise-onleft").css({
      height: 2 * wReiseTile + 10
    });
  };

  return UberunsReise;

})(ChildPage);

window.core.insertChildPage(new UberunsReise());
