// Generated by CoffeeScript 1.12.6
var UberunsReise,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

UberunsReise = (function(superClass) {
  extend(UberunsReise, superClass);

  function UberunsReise() {
    this.reisehack = bind(this.reisehack, this);
    this.setupMap = bind(this.setupMap, this);
    this.onDOMVisible = bind(this.onDOMVisible, this);
    this.core = window.core;
    this.core.requestFunction("ContentViewer.requestInstance", (function(_this) {
      return function(cView) {
        return _this.contentViewer = cView();
      };
    })(this));
    this.metadata = {
      r1: {
        title: "Spanien",
        caption: "Konzertreise 2014",
        textID: "#spanien",
        thumbnail: "/img/spanien.jpg",
        linkBilder: "#!/bilder/kategorie/by-title/konzertreise-2014"
      },
      r2: {
        title: "Tschechien und Polen",
        caption: "Konzertreise 2015",
        textID: "#tschechien-polen",
        linkBilder: "#!/bilder/kategorie/by-title/konzertreise-2015",
        thumbnail: "/img/tschechien-polen.jpg"
      },
      r3: {
        title: "Frankreich, England, Guernsey",
        caption: "Konzertreise 2016",
        textID: "#frankreich-england",
        thumbnail: "/img/england-guernsey.jpg",
        linkBilder: "#!/bilder/kategorie/by-title/konzertreise-2016"
      }
    };
  }

  UberunsReise.prototype.onLoad = function() {
    var i, j, results;
    window.core.setMetaDesc("Konzertreise", "Konzertreise");
    $.when($.getScript("/code/jquery.vmap.js"), $.getScript("/code/jquery.vmap.europe.js"), $.getScript("/code/jquery.vmap.world.js"), $.Deferred(function(deferred) {
      return $(deferred.resolve);
    })).done(function() {
      return window.core.release();
    });
    results = [];
    for (i = j = 0; j <= 2; i = ++j) {
      results.push($(".reise-tile").eq(i).hover(function() {
        return $(this).find("h1").addClass("fade");
      }, function() {
        return $(this).find("h1").removeClass("fade");
      }));
    }
    return results;
  };

  UberunsReise.prototype.onDOMVisible = function() {
    if (!(window.ie || window.mobile())) {
      this.reisehack();
      $(window).on("resize", this.reisehack);
    }
    return this.setupMap();
  };

  UberunsReise.prototype.onUnloadChild = function() {
    window.core.revMetaDesc();
    if (!(window.ie || window.mobile)) {
      return $(window).off("resize", this.reisehack);
    }
  };

  UberunsReise.prototype.notifyHashChange = function(newHash) {
    var elem, h, metaobj, number, offs, w;
    if (newHash.lastIndexOf("/info/", 0) === 0) {
      number = parseInt(newHash.substr(6, newHash.length));
      metaobj = void 0;
      switch (number) {
        case 1:
          metaobj = this.metadata.r1;
          break;
        case 2:
          metaobj = this.metadata.r2;
          break;
        case 3:
          metaobj = this.metadata.r3;
      }
      w = $(window).width();
      h = $(window).height();
      elem = $("#rt" + number);
      offs = elem.offset();
      this.contentViewer.open({
        left: function() {
          return (w / 2) - (1000 / 2);
        },
        top: function() {
          return (h / 2) - (600 / 2);
        },
        right: function() {
          return (w / 2) - (1000 / 2);
        },
        height: function() {
          return 600 + "px";
        },
        chapter: false,
        title: metaobj.title,
        caption: metaobj.caption,
        revertHash: "#!/uberuns/reise",
        content: $("#content-reise").html(),
        animate: false
      });
      return this.populate(metaobj.textID, metaobj.linkBilder, metaobj.thumbnail);
    }
  };

  UberunsReise.prototype.populate = function(textPtr, bilderLink, thumbnail) {
    $(".reise-left-tile").removeClass("reise-left-tile-inactive");
    if (bilderLink === -1) {
      $(".reise-left-tile").addClass("reise-left-tile-inactive");
    } else {
      $(".reise-left-tile").attr("href", bilderLink);
    }
    $(".reise-left-tile img").attr("src", thumbnail);
    $(".reise-right-titel").html($(textPtr).children("h1").html());
    return $(".reise-right-content").html($(textPtr).children("p").html());
  };

  UberunsReise.prototype.acquireLoadingLock = function() {
    return true;
  };

  UberunsReise.prototype.setupMap = function() {
    var hReiseTile, wReiseTile;
    wReiseTile = $(".reise-tile").eq(0).width();
    hReiseTile = $(".reise-tile").eq(0).height();
    $("#map").css({
      height: hReiseTile,
      width: wReiseTile
    });
    $('#map').vectorMap({
      map: 'europe_en',
      backgroundColor: "#1a171a",
      borderColor: '#1a171a',
      borderWidth: 0,
      color: '#ffffff',
      hoverColor: '#999999',
      enableZoom: false,
      showTooltip: true,
      colors: {
        de: "#199250",
        es: "#305596",
        gb: "#199250",
        at: "#199250",
        dk: "#199250",
        cz: "#199250",
        fr: "#199250",
        it: "#199250",
        se: "#199250",
        no: "#199250",
        nl: "#199250",
        ch: "#199250",
        hu: "#199250",
        si: "#199250",
        hr: "#199250",
        lu: "#199250",
        be: "#199250",
        pl: "#199250"
      }
    });
    return $("#map-world").vectorMap({
      map: 'world_en',
      backgroundColor: "#1a171a",
      borderColor: '#1a171a',
      color: '#ffffff',
      hoverColor: '#999999',
      enableZoom: false,
      showTooltip: true,
      colors: {
        de: "#199250",
        es: "#305596",
        gb: "#199250",
        at: "#199250",
        dk: "#199250",
        cz: "#199250",
        fr: "#199250",
        it: "#199250",
        se: "#199250",
        no: "#199250",
        nl: "#199250",
        ch: "#199250",
        hu: "#199250",
        si: "#199250",
        hr: "#199250",
        us: "#199250",
        lu: "#199250",
        be: "#199250",
        pl: "#199250"
      }
    });
  };

  UberunsReise.prototype.reisehack = function() {
    var wReiseTile;
    wReiseTile = $(".reise-tile").eq(0).height();
    return $("#reise-onleft").css({
      height: 2 * wReiseTile + 10
    });
  };

  return UberunsReise;

})(ChildPage);

window.core.insertChildPage(new UberunsReise());
