// Generated by CoffeeScript 1.7.1
var UberunsTeam,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

UberunsTeam = (function(_super) {
  __extends(UberunsTeam, _super);

  function UberunsTeam() {
    UberunsTeam.__super__.constructor.call(this);
    this.linkIDMapper = [["johannes", 0], ["lechner", 1], ["noah", 2], ["orga", 3], ["clt", 4]];
  }

  UberunsTeam.clickedPreviously = null;

  UberunsTeam.prototype.onLoad = function() {
    return $(".reise-tile").hover(function() {
      return setTimeout((function(_this) {
        return function() {
          if ($(_this).mouseIsOver()) {
            return window.location.hash = $(_this).children("a").attr("href");
          }
        };
      })(this), 350);
    });
  };

  UberunsTeam.prototype.onUnloadChild = function() {};

  UberunsTeam.prototype.notifyHashChange = function(newHash) {
    var el, _i, _len, _ref;
    _ref = this.linkIDMapper;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      el = _ref[_i];
      if (("/" + el[0]) === newHash) {
        this.reset(true);
        this.handle(el[1]);
        this.clickedPreviously = el[1];
        return;
      }
    }
    if (newHash === "/" || newHash === "") {
      return this.reset();
    }
  };

  UberunsTeam.prototype.handle = function(id) {
    var childs;
    childs = document.querySelectorAll(".reise-tile");
    $(childs[id]).children(".before-transition").addClass("invisible");
    return $(childs[id]).children(".after-transition").css({
      display: "block"
    });
  };

  UberunsTeam.prototype.reset = function(force) {
    if (force == null) {
      force = false;
    }
    if (!force) {
      $(".reise-tile").eq(this.clickedPreviously).children(".before-transition").removeClass("invisible");
      return $(".reise-tile").eq(this.clickedPreviously).children(".after-transition").css({
        display: "none"
      });
    } else {
      $(".reise-tile").eq(this.clickedPreviously).children(".before-transition").removeClass("invisible");
      return $(".reise-tile").eq(this.clickedPreviously).children(".after-transition").css({
        display: "none"
      });
    }
  };

  return UberunsTeam;

})(ChildPage);

window.core.insertChildPage(new UberunsTeam());
