// Generated by CoffeeScript 1.12.6
var UberunsTeam,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

UberunsTeam = (function(superClass) {
  extend(UberunsTeam, superClass);

  function UberunsTeam() {
    UberunsTeam.__super__.constructor.call(this);
    this.linkIDMapper = [["johannes", 0], ["lechner", 1], ["lukas", 2], ["orga", 3], ["clt", 4], ["choristen", 5]];
  }

  UberunsTeam.clickedPreviously = null;

  UberunsTeam.prototype.onLoad = function() {
    return window.core.setMetaDesc("Eine starke Gemeinschaft", "Team");
  };

  UberunsTeam.prototype.onUnloadChild = function() {
    return window.core.revMetaDesc();
  };

  UberunsTeam.prototype.notifyHashChange = function(newHash) {
    var el, i, len, ref;
    ref = this.linkIDMapper;
    for (i = 0, len = ref.length; i < len; i++) {
      el = ref[i];
      if (("/" + el[0]) === newHash) {
        this.reset(true);
        this.handle(el[1]);
        this.clickedPreviously = el[1];
        return;
      }
    }
    if (newHash === "/" || newHash === "") {
      return this.reset();
    }
  };

  UberunsTeam.prototype.handle = function(id) {
    var childs;
    childs = document.querySelectorAll(".reise-tile");
    $(childs[id]).children(".before-transition").addClass("invisible");
    return $(childs[id]).children(".after-transition").css({
      display: "block"
    });
  };

  UberunsTeam.prototype.reset = function(force) {
    if (force == null) {
      force = false;
    }
    if (!force) {
      $(".reise-tile").eq(this.clickedPreviously).children(".before-transition").removeClass("invisible");
      return $(".reise-tile").eq(this.clickedPreviously).children(".after-transition").css({
        display: "none"
      });
    } else {
      $(".reise-tile").eq(this.clickedPreviously).children(".before-transition").removeClass("invisible");
      return $(".reise-tile").eq(this.clickedPreviously).children(".after-transition").css({
        display: "none"
      });
    }
  };

  return UberunsTeam;

})(ChildPage);

window.core.insertChildPage(new UberunsTeam());
