// Generated by CoffeeScript 1.7.1
var Uberuns,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Uberuns = (function(_super) {
  __extends(Uberuns, _super);

  function Uberuns() {
    this.core = window.core;
    this.oneshot = true;
  }

  Uberuns.prototype.onDOMVisible = function() {};

  Uberuns.prototype.notifyHashChange = function(newHash) {
    var load;
    if (this.oneshot) {
      load = this.core.requestFunction("Tile.load", function(load) {
        newHash = newHash.substr(1, newHash.length);
        return load("Über uns", "uberuns-" + newHash, true);
      }, $.noop);
    }
    return this.oneshot = false;
  };

  Uberuns.prototype.onLoad = function() {
    $(".testblock").hover(function() {
      return setTimeout(function() {
        if ($(".testblock").is(":hover")) {
          return $(".testblock").animate({
            opacity: 0
          }, 350);
        }
      }, 700);
    }, function() {
      return $(this).animate({
        opacity: 1
      }, 350);
    });
    return window.core.release();
  };

  Uberuns.prototype.mouseEnter = function() {};

  return Uberuns;

})(ChildPage);

window.core.insertChildPage(new Uberuns());
