// Generated by CoffeeScript 1.7.1
var UberunsReise,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

UberunsReise = (function(_super) {
  __extends(UberunsReise, _super);

  function UberunsReise() {
    this.reisehack = __bind(this.reisehack, this);
    this.core = window.core;
    this.showMap = false;
  }

  UberunsReise.prototype.onLoad = function() {
    return $.when($.getScript("/code/jquery.vmap.europe.js"), $.getScript("/code/jquery.vmap.min.js"), $.Deferred(function(deferred) {
      return $(deferred.resolve);
    })).then(function() {
      console.log("sucess");
      this.showMap = true;
      return window.core.release();
    }, function() {
      console.log("fail");
      return window.core.release();
    });
  };

  UberunsReise.prototype.onDOMVisible = function() {
    console.log("in onASDvisible");
    this.reisehack();
    $(window).on("resize", this.reisehack);
    if (this.showMap) {
      this.setupMap();
      return $(window).on("resize", this.setupMap);
    }
  };

  UberunsReise.prototype.onUnloadChild = function() {
    $(window).off("resize", this.reisehack);
    return $(window).off("resize", this.setupMap);
  };

  UberunsReise.prototype.notifyHashChange = function(newHash) {};

  UberunsReise.prototype.acquireLoadingLock = function() {
    return true;
  };

  UberunsReise.prototype.setupMap = function() {
    var hReiseTile, wReiseTile;
    wReiseTile = $(".reise-tile").eq(0).width();
    hReiseTile = $(".reise-tile").eq(0).height();
    $("#map").css({
      height: hReiseTile,
      width: wReiseTile
    });
    console.log(hReiseTile);
    console.log($("#map").css("height"));
    return $('#map').vectorMap({
      map: 'europe_en',
      backgroundColor: null,
      color: '#ffffff',
      hoverColor: '#999999',
      enableZoom: false,
      showTooltip: false
    });
  };

  UberunsReise.prototype.reisehack = function() {
    var wReiseTile;
    wReiseTile = $(".reise-tile").eq(0).height();
    return $("#reise-onleft").css({
      height: 2 * wReiseTile + 10
    });
  };

  return UberunsReise;

})(ChildPage);

window.core.insertChildPage(new UberunsReise());
