// Generated by CoffeeScript 1.7.1
var Uberuns,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Uberuns = (function(_super) {
  __extends(Uberuns, _super);

  function Uberuns() {
    this.core = window.core;
    this.core.state["uberuns-doesnothing"] = true;
  }

  Uberuns.prototype.onDOMVisible = function() {
    if (window.ie) {
      $(".reise-imgcontainer").css({
        display: "none"
      });
      return $(".reise-sidebarcontainer").css({
        display: "none"
      });
    }
  };

  Uberuns.prototype.notifyHashChange = function(newHash) {};

  Uberuns.prototype.onLoad = function() {
    $(".hiddentext").hover(function() {
      return $(".hiddentext").addClass("visible");
    }, function() {
      return $(".hiddentext").removeClass("visible");
    });
    $(".icon-container").click(function(event) {
      $("#uberuns").css({
        "margin-left": -($(window).width() * 0.06 + $(".deadcenter").width() - 50)
      });
      setTimeout((function(_this) {
        return function() {
          return location.hash = $(_this).attr("href");
        };
      })(this), 1000);
      event.stopPropagation();
      return event.preventDefault();
    });
    return window.core.release();
  };

  Uberuns.prototype.mouseEnter = function() {};

  return Uberuns;

})(ChildPage);

window.core.insertChildPage(new Uberuns());
