// Generated by CoffeeScript 1.7.1
var Unterstutzen,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Unterstutzen = (function(_super) {
  __extends(Unterstutzen, _super);

  function Unterstutzen() {
    Unterstutzen.__super__.constructor.call(this);
  }

  Unterstutzen.prototype.onLoad = function() {
    return window.core.setMetaDesc("M&ouml;glichkeiten der Unterst&ouml;tzung", "Unterst&uuml;tzen");
  };

  Unterstutzen.prototype.onUnloadChild = function() {
    return window.core.revMetaDesc();
  };

  return Unterstutzen;

})(ChildPage);

window.core.insertChildPage(new Unterstutzen());
